bootnodes:
- bootnode00:
    k8s:
      nodePort_rpc: 30008
      nodePort_ipc: 30009
      replicas: 1
      nodekeyhex: "091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322"
      verbosity: 9
    geth:
      storage_size: 20
      Eth_Etherbase: "0x1e2510200cc63faf248150530d16415a52757f50"
      Eth_Password: "123"
      Node_UserIdent: bootnode
      Node_DataDir: /etc/testnet/bootnode
      Node_HTTPPort: 8545
      Node_WSPort: 8546
      NodeP2P_ListenAddr: 30301
      NodeP2P_DiscoveryAddr: 30303
      Dashboard_Port: 8080
      Dashboard_Refresh: 3000000000
nodes:
- miner01:
    k8s:
      nodePort_rpc: 30001
      nodePort_ipc: 30002
      replicas: 1
    geth:
      storage_size: 20
      Eth_Etherbase: "0xc11ba4c7c24f70e7a581c7daa92eac108099acec"
      Eth_Password: "123"
      Node_UserIdent: miner01
      Node_DataDir: /etc/testnet/miner01
      Node_HTTPPort: 8545
      Node_WSPort: 8546
      NodeP2P_DiscoveryAddr: 30303
      Dashboard_Port: 8080
      Dashboard_Refresh: 3000000000
- miner02:
    k8s:
      nodePort_rpc: 30004
      nodePort_ipc: 30005
      replicas: 1
    geth:
      storage_size: 20
      Eth_Etherbase: "0x4c92786b90d848eaa3f4ef46918af724a309ae79"
      Eth_Password: "123"
      Node_UserIdent: miner02
      Node_DataDir: /etc/testnet/miner02
      Node_HTTPPort: 8545
      Node_WSPort: 8546
      NodeP2P_DiscoveryAddr: 30303
      Dashboard_Port: 8080
      Dashboard_Refresh: 3000000000
- miner03:
    k8s:
      nodePort_rpc: 30006
      nodePort_ipc: 30007
      replicas: 1
    geth:
      storage_size: 20
      Eth_Etherbase: "0x4e7afbdc9413eeb582b3f1be49d652fa714484da"
      Eth_Password: "123"
      Node_UserIdent: miner03
      Node_DataDir: /etc/testnet/miner03
      Node_HTTPPort: 8545
      Node_WSPort: 8546
      NodeP2P_DiscoveryAddr: 30303
      Dashboard_Port: 8080
      Dashboard_Refresh: 3000000000
monitor:
  name: monitor
  ws_secret: "123"
  storage_size: 10
  # verbosity can be within [0..3]
  verbosity: 3
  k8s:
    nodePort: 30100
    externalPort: 80
    configMap:
      name: genesis-config
      items:
      - key: genesis-geth.json
        path: genesis-geth.json
explorer:
  name: explorer
  storage_size: 10
  explorerNode: miner01
  explorerHTTPPort: 8545
  k8s:
    nodePort: 30101
    externalPort: 80
    configMap:
      name: explorer-config
      items:
      - key: config.json
        path: config.json
keystore:
  secret: false
  items:
    "0xc11ba4c7c24f70e7a581c7daa92eac108099acec": UTC--2019-06-04T13-52-41.551926270Z--c11ba4c7c24f70e7a581c7daa92eac108099acec
    "0x4c92786b90d848eaa3f4ef46918af724a309ae79": UTC--2019-06-04T13-52-48.511656735Z--4c92786b90d848eaa3f4ef46918af724a309ae79
    "0x4e7afbdc9413eeb582b3f1be49d652fa714484da": UTC--2019-06-04T13-52-53.567362092Z--4e7afbdc9413eeb582b3f1be49d652fa714484da
    "0x2da602397dbcd7b3f3efec474124746e8e913c44": UTC--2019-06-04T13-53-00.073235074Z--2da602397dbcd7b3f3efec474124746e8e913c44
    "0x1e2510200cc63faf248150530d16415a52757f50": UTC--2019-06-04T13-53-06.513321284Z--1e2510200cc63faf248150530d16415a52757f50
geth:
  version: v1.8.27
  network:
    id: 123456
    period: 15
    verbosity: 3
    epoch: 30000
    nonce: "0x0"
    timestamp: "0x5cdec502"
    gasLimit: "0x82F79CD9000"
    gasFloor: "0x82F79CD9000"
    gasCeil: "0x82F79CD9000"
    gasPrice: "0x0"
    # public (true|false) is it a public network?
    public: false
    # cross_net (true|false) is it cross different network (cloud)
    cross_net: true
  # hex value of initial difficulty defined in the genesis block
  difficulty: "0x1"
  verbosity: 3
  targetgaslimit: '9000000000000'
